// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWBre44lYj_O8TQl0WlKlSM88CaaQIIg',
    appId: '1:991029501066:web:990b518db279fb874e6173',
    messagingSenderId: '991029501066',
    projectId: 'zuma-7d556',
    authDomain: 'zuma-7d556.firebaseapp.com',
    storageBucket: 'zuma-7d556.firebasestorage.app',
    measurementId: 'G-QYJ36D4M5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXiJLc0t9J6XuX7OCcfzi0bmhI2ZPClcI',
    appId: '1:991029501066:android:e361e5ed078399c44e6173',
    messagingSenderId: '991029501066',
    projectId: 'zuma-7d556',
    storageBucket: 'zuma-7d556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhLibnLUmBHv3f201rih_PJe99-NrZj3E',
    appId: '1:991029501066:ios:d2d136abd5d0b9e14e6173',
    messagingSenderId: '991029501066',
    projectId: 'zuma-7d556',
    storageBucket: 'zuma-7d556.firebasestorage.app',
    iosClientId: '991029501066-6iv0tf013e3b347gkphvuc9j3dnmt2fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.zuma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhLibnLUmBHv3f201rih_PJe99-NrZj3E',
    appId: '1:991029501066:ios:d2d136abd5d0b9e14e6173',
    messagingSenderId: '991029501066',
    projectId: 'zuma-7d556',
    storageBucket: 'zuma-7d556.firebasestorage.app',
    iosClientId: '991029501066-6iv0tf013e3b347gkphvuc9j3dnmt2fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.zuma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZWBre44lYj_O8TQl0WlKlSM88CaaQIIg',
    appId: '1:991029501066:web:9743afe0198e1cf44e6173',
    messagingSenderId: '991029501066',
    projectId: 'zuma-7d556',
    authDomain: 'zuma-7d556.firebaseapp.com',
    storageBucket: 'zuma-7d556.firebasestorage.app',
    measurementId: 'G-GMTSENZX73',
  );
}
